import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigureAmplifyClientSide } from "@/components/ConfigureAmplifyClientSide";
import { Navbar } from "@/components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <ConfigureAmplifyClientSide />
      <body className={inter.className}>
        <>
          <Navbar />
          <div className="py-8 px-16 bg-slate-100">{children}</div>
        </>
      </body>
    </html>
  );
}
